// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/design/NoirGold.tsx": () => import("../components/mockups/design/NoirGold.tsx"),
  "./components/mockups/design/ObsidianIvory.tsx": () => import("../components/mockups/design/ObsidianIvory.tsx"),
  "./components/mockups/design/PlatinumFrost.tsx": () => import("../components/mockups/design/PlatinumFrost.tsx")
};
